### PR TITLE
add crstrings library

### PR DESCRIPTION
**Pull request by RaduBerinde**
This library contains some general convenience functions related to
strings and string slices.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/crlib/2)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Let me know if there are other utilities that you wish you had in the standard `strings` library. I plan to use some of these in Pebble soon.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/crlib/2#-:-O5y2WAn6TM8qwYlGwZB:bg7igkv)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`crstrings/utils.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/crlib/2#-O5y1VMW5QISkyX1dMlh:-O5y1VMW5QISkyX1dMli:b-xbp86) ([raw file](https://github.com/cockroachdb/crlib/blob/f49c5dd3d862ba99955010b49ffb46ae5be7a779/crstrings/utils.go#L73)):*
> ```Go
> //
> //	fmt.Sprintf("%s%s", a, crstrings.PrependIfNotEmpty(", ", b))
> func PrependIfNotEmpty(prefix, s string) string {
> ```

I understand what this is trying to do, but this sample usage did not help me understand the value.
Was this meant to help with formatting loops in prepending a separator on iterations after the first iteration?

Similar question for `AppendIfNotEmpty`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/crlib/2)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`crstrings/utils.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/crlib/2#-O5y1VMW5QISkyX1dMlh:-O5y4lKG5j3HXDmJwy2k:b-5db4l6) ([raw file](https://github.com/cockroachdb/crlib/blob/f49c5dd3d862ba99955010b49ffb46ae5be7a779/crstrings/utils.go#L73)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I understand what this is trying to do, but this sample usage did not help me understand the value.
Was this meant to help with formatting loops in prepending a separator on iterations after the first iteration?

Similar question for `AppendIfNotEmpty`.
</blockquote></details>

It's mostly for printf statements. E.g. `Sprintf("%s%s %s%s", x, PrependIfNotEmpty(", ", y), z, PrependIfNotEmptry(", ", u)` That would normally take 5+ lines of code.

**Comment by RaduBerinde** [comment]
*[`crstrings/utils.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/crlib/2#-O5y1VMW5QISkyX1dMlh:-O5yBl4Q81ajkIsMWozN:b-lslyeo) ([raw file](https://github.com/cockroachdb/crlib/blob/f49c5dd3d862ba99955010b49ffb46ae5be7a779/crstrings/utils.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's mostly for printf statements. E.g. `Sprintf("%s%s %s%s", x, PrependIfNotEmpty(", ", y), z, PrependIfNotEmptry(", ", u)` That would normally take 5+ lines of code.
</blockquote></details>

Though maybe it would be cleaner to do `Sprintf("%s%s%s", a, crstrings.If(b != "", ", "), b)`

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/crlib/2)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @RaduBerinde)

___
*[`crstrings/utils.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/crlib/2#-O5y1VMW5QISkyX1dMlh:-O5y_Kgo48pf5HuBI2AQ:bhhc40q) ([raw file](https://github.com/cockroachdb/crlib/blob/f49c5dd3d862ba99955010b49ffb46ae5be7a779/crstrings/utils.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Though maybe it would be cleaner to do `Sprintf("%s%s%s", a, crstrings.If(b != "", ", "), b)`
</blockquote></details>

Thanks for the clarification. Either is fine by me.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/crlib/2)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`crstrings/utils.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/crlib/2#-O5y1VMW5QISkyX1dMlh:-O5yafBDBKhf6_EBEI3t:b5sm1d6) ([raw file](https://github.com/cockroachdb/crlib/blob/f49c5dd3d862ba99955010b49ffb46ae5be7a779/crstrings/utils.go#L73)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Thanks for the clarification. Either is fine by me.
</blockquote></details>

I replaced them with a single `WithSep(a, separator, b)` function.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/crlib/2#-:-O5ypV-OAiueIcM7hurD:b-814g8k)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @itsbilal, @jbowens, and @sumeerbhola)

**Pull request merged**
